#string
bind = "0.0.0.0:8081"
#string array
domains = ["api.mgtv.com","api.weibo.cn.","weibo.cn.","taobao.com.","www.baidu.com.","www.taobao.com."]
#bool
mysql_enable = false
#string
server_log = "./httpdispatcher.server.log"
query_log = "./httpdispatcher.query.log"
httpd_log = "./httpdispatcher.httpd.log"
querylog_format = "%{time:2006-01-02T15:04:05} %{shortfile}|%{shortfunc} %{level:.4s} %{id:03x}%{message}"
serverlog_format = "%{time:2006-01-02T15:04:05} %{shortfile}|%{shortfunc} %{level:.4s} %{id:03x}%{message}"
log_level = "WARNING"

[mysql]
#string
mysql_host = "127.0.0.1"
#int
mysql_port = 3306
#string
mysql_database = "httpDispatcher_v1"
#string
mysql_user = "root"
#string
mysql_password = ""
#string array
domains_in_mysql = ["api.weibo.cn.","weibo.cn."]
