#string
bind = "0.0.0.0:8080"
#string array
domains = ["api.weibo.cn.","weibo.cn.","taobao.com.","www.baidu.com.","www.taobao.com."]
#bool
mysql_enable = false
#string
server_log = "./httpdispacher.server.log"
query_log = "./httpdispacher.query.log"
querylog_format = "%{time:2006-01-02T15:04:05} %{shortfile}|%{shortfunc} %{level:.4s} %{id:03x} %{message}"
serverlog_format = "%{time:2006-01-02T15:04:05} %{shortfile}|%{shortfunc} %{level:.4s} %{id:03x} %{message}"
log_level = "INFO"

[mysql]
#string
mysql_host = "127.0.0.1"
#int
mysql_port = 3306
#string
mysql_database = "httpDispacher_v1"
#string
mysql_user = "root"
#string
mysql_password = ""
#string array
domains_in_mysql = ["api.weibo.cn.","weibo.cn."]
